"""Make photos.target_id nullable

Revision ID: 0922e24544c8
Revises: ef05cf04ef0f
Create Date: 2025-11-08 20:15:18.747900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0922e24544c8'
down_revision: Union[str, Sequence[str], None] = 'ef05cf04ef0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('photos', 'target_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('photos', 'target_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
