"""Implement new Q1Q2 vibe system

Revision ID: 0a021a451925
Revises: 646e1995ed7d
Create Date: 2025-11-08 22:15:00.123456
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0a021a451925'
down_revision = '646e1995ed7d' # <-- Make sure this matches the 'Revises:' ID above
branch_labels = None
depends_on = None

# Define the new ENUM types we are creating
worthitratingenum = postgresql.ENUM('skip', 'maybe', 'worth_it', name='worthitratingenum')

# Define the old ENUM we are dropping
viberatingenum = postgresql.ENUM('empty', 'studying', 'lively', 'packed', name='viberatingenum')


def upgrade() -> None:
    # ### commands auto-generated by Alembic - please adjust ###

    # 1. Create the new ENUM type for Q1
    worthitratingenum.create(op.get_bind())

    # 2. Add new columns to 'events' table
    #    We MUST provide a server_default for NOT NULL columns
    op.add_column('events', sa.Column(
        'vibe_question_1_text', 
        sa.String(), 
        nullable=False, 
        server_default="Worth the trip right now?"
    ))
    op.add_column('events', sa.Column(
        'vibe_question_1_options', 
        sa.ARRAY(sa.String()), 
        nullable=False, 
        server_default='{"👎 Skip", "🤷 Maybe", "👍 Worth it"}'
    ))
    op.add_column('events', sa.Column('vibe_question_2_text', sa.String(), nullable=True))
    op.add_column('events', sa.Column('vibe_question_2_options', sa.ARRAY(sa.String()), nullable=True))

    # 3. Add new columns to 'vibes' table
    #    We make it nullable=True first, then update, then set to NOT NULL
    #    ...OR for a hackathon, just set a server_default.
    op.add_column('vibes', sa.Column(
        'worth_it_rating', 
        sa.Enum('skip', 'maybe', 'worth_it', name='worthitratingenum'), 
        nullable=False,
        server_default='maybe' # Default all old vibes to 'maybe'
    ))
    op.add_column('vibes', sa.Column('contextual_answer', sa.String(), nullable=True))

    # 4. Drop the old vibe columns
    op.drop_column('vibes', 'rating_enum')
    op.drop_column('vibes', 'food_rating')
    op.drop_column('vibes', 'crowd_rating')
    op.drop_column('vibes', 'queue_rating')

    # 5. Drop the old ENUM type
    viberatingenum.drop(op.get_bind())

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto-generated by Alembic - please adjust ###

    # 1. Re-create the old ENUM type
    viberatingenum.create(op.get_bind())

    # 2. Add the old columns back (as nullable)
    op.add_column('vibes', sa.Column('queue_rating', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('vibes', sa.Column('crowd_rating', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('vibes', sa.Column('food_rating', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('vibes', sa.Column(
        'rating_enum', 
        sa.Enum('empty', 'studying', 'lively', 'packed', name='viberatingenum'), 
        autoincrement=False, 
        nullable=True # Set to True to avoid errors
    ))

    # 3. Drop the new columns
    op.drop_column('vibes', 'contextual_answer')
    op.drop_column('vibes', 'worth_it_rating')
    op.drop_column('events', 'vibe_question_2_options')
    op.drop_column('events', 'vibe_question_2_text')
    op.drop_column('events', 'vibe_question_1_options')
    op.drop_column('events', 'vibe_question_1_text')

    # 4. Drop the new ENUM type
    worthitratingenum.drop(op.get_bind())

    # ### end Alembic commands ###