"""Add event_feedback table

Revision ID: 1e406422c682
Revises: 7d026e996dbc
Create Date: 2025-11-08 23:57:30.060278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e406422c682'
down_revision: Union[str, Sequence[str], None] = '7d026e996dbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_feedback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('anon_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('review', sa.String(), nullable=True),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['anon_id'], ['users_anon.anon_id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_feedback_anon_id'), 'event_feedback', ['anon_id'], unique=False)
    op.create_index(op.f('ix_event_feedback_event_id'), 'event_feedback', ['event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_feedback_event_id'), table_name='event_feedback')
    op.drop_index(op.f('ix_event_feedback_anon_id'), table_name='event_feedback')
    op.drop_table('event_feedback')
    # ### end Alembic commands ###
