"""Re-add space vibes, make all vibe fields nullable

Revision ID: 7d026e996dbc
Revises: 0a021a451925
Create Date: 2025-11-08 22:42:06.889996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7d026e996dbc'
down_revision: Union[str, Sequence[str], None] = '0a021a451925'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    
    # Define the old ENUM
    viberatingenum_type = sa.Enum('empty', 'studying', 'lively', 'packed', name='viberatingenum')
# Create it in the database
    viberatingenum_type.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vibes', sa.Column('rating_enum', viberatingenum_type, nullable=True))
    op.add_column('vibes', sa.Column('food_rating', sa.Integer(), nullable=True))
    op.add_column('vibes', sa.Column('crowd_rating', sa.Integer(), nullable=True))
    op.add_column('vibes', sa.Column('queue_rating', sa.Integer(), nullable=True))
    op.alter_column('vibes', 'worth_it_rating', nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vibes', 'worth_it_rating',
               existing_type=postgresql.ENUM('skip', 'maybe', 'worth_it', name='worthitratingenum'),
               nullable=False,
               existing_server_default=sa.text("'maybe'::worthitratingenum"))
    op.drop_column('vibes', 'queue_rating')
    op.drop_column('vibes', 'crowd_rating')
    op.drop_column('vibes', 'food_rating')
    op.drop_column('vibes', 'rating_enum')
    # ### end Alembic commands ###
