"""Initial models

Revision ID: 9ff8085f3ba8
Revises: 
Create Date: 2025-11-08 01:43:28.619491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9ff8085f3ba8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spaces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users_anon',
    sa.Column('anon_id', sa.UUID(), nullable=False),
    sa.Column('created_ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('anon_id')
    )
    op.create_table('chats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('anon_id', sa.UUID(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('moderation_flag', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['anon_id'], ['users_anon.anon_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chats_anon_id'), 'chats', ['anon_id'], unique=False)
    op.create_index(op.f('ix_chats_channel'), 'chats', ['channel'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('location_lat', sa.Float(), nullable=True),
    sa.Column('location_lon', sa.Float(), nullable=True),
    sa.Column('location_name', sa.String(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users_anon.anon_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('photos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('target_type', sa.Enum('event', 'space', name='vibetargetenum'), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('anon_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('nsfw_score', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('approved', 'flagged', 'removed', name='photostatusenum'), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['anon_id'], ['users_anon.anon_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_photos_anon_id'), 'photos', ['anon_id'], unique=False)
    op.create_index(op.f('ix_photos_target_id'), 'photos', ['target_id'], unique=False)
    op.create_table('vibes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('target_type', sa.Enum('event', 'space', name='vibetargetenum'), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('anon_id', sa.UUID(), nullable=False),
    sa.Column('rating_enum', sa.Enum('empty', 'studying', 'lively', 'packed', name='viberatingenum'), nullable=False),
    sa.Column('food_rating', sa.Integer(), nullable=True),
    sa.Column('crowd_rating', sa.Integer(), nullable=True),
    sa.Column('queue_rating', sa.Integer(), nullable=True),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['anon_id'], ['users_anon.anon_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vibes_anon_id'), 'vibes', ['anon_id'], unique=False)
    op.create_index(op.f('ix_vibes_target_id'), 'vibes', ['target_id'], unique=False)
    op.create_table('rsvps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('anon_id', sa.UUID(), nullable=False),
    sa.Column('visibility', sa.Enum('public', 'private', name='rsvpvisibilityenum'), nullable=False),
    sa.Column('status', sa.Enum('going', 'interested', 'not_interested', name='rsvpstatusenum'), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['anon_id'], ['users_anon.anon_id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rsvps_anon_id'), 'rsvps', ['anon_id'], unique=False)
    op.create_index(op.f('ix_rsvps_event_id'), 'rsvps', ['event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rsvps_event_id'), table_name='rsvps')
    op.drop_index(op.f('ix_rsvps_anon_id'), table_name='rsvps')
    op.drop_table('rsvps')
    op.drop_index(op.f('ix_vibes_target_id'), table_name='vibes')
    op.drop_index(op.f('ix_vibes_anon_id'), table_name='vibes')
    op.drop_table('vibes')
    op.drop_index(op.f('ix_photos_target_id'), table_name='photos')
    op.drop_index(op.f('ix_photos_anon_id'), table_name='photos')
    op.drop_table('photos')
    op.drop_table('events')
    op.drop_index(op.f('ix_chats_channel'), table_name='chats')
    op.drop_index(op.f('ix_chats_anon_id'), table_name='chats')
    op.drop_table('chats')
    op.drop_table('users_anon')
    op.drop_table('spaces')
    # ### end Alembic commands ###
