"""Add role to user_profiles

Revision ID: e291e3e8fe07
Revises: 698f173a217e
Create Date: 2025-11-08 18:30:00.000000
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e291e3e8fe07'
down_revision = '698f173a217e'
branch_labels = None
depends_on = None

# Define the new ENUM type here
role_enum_type = sa.Enum('student', 'organizer', name='roleenum')


def upgrade() -> None:
    # ### commands auto-generated by Alembic - please adjust ###

    # 1. Create the new "roleenum" type in PostgreSQL
    role_enum_type.create(op.get_bind())

    # 2. Add the column, using the new type.
    #    We add server_default='student' because the column is NOT NULL
    #    and your model has a default. This is required for existing rows.
    op.add_column(
        'user_profiles',
        sa.Column(
            'role',
            role_enum_type,
            nullable=False,
            server_default='student'
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto-generated by Alembic - please adjust ###

    # 1. Drop the column first
    op.drop_column('user_profiles', 'role')

    # 2. Drop the "roleenum" type from PostgreSQL
    role_enum_type.drop(op.get_bind())

    # ### end Alembic commands ###