"""Add auth_link table

Revision ID: f2d91bac1371
Revises: 9ff8085f3ba8
Create Date: 2025-11-08 01:54:15.618714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2d91bac1371'
down_revision: Union[str, Sequence[str], None] = '9ff8085f3ba8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_links',
    sa.Column('auth0_sub', sa.String(), nullable=False),
    sa.Column('anon_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['anon_id'], ['users_anon.anon_id'], ),
    sa.PrimaryKeyConstraint('auth0_sub'),
    sa.UniqueConstraint('anon_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auth_links')
    # ### end Alembic commands ###
