import enum
import uuid
from sqlalchemy import (
    Column, String, DateTime, ForeignKey, Enum,
    Float, Integer, func, Boolean
)
from sqlalchemy.dialects.postgresql import UUID, ARRAY
from sqlalchemy.orm import relationship, backref

# Import the Base class from our db.py file
from app.db import Base

# --- Enums (FIXED) ---

class VibeTargetEnum(enum.Enum):
    event = "event"
    space = "space"
    profile = "profile"
    banner = "banner"

# This is the NEW Q1 enum
class WorthItRatingEnum(enum.Enum):
    skip = "skip"
    maybe = "maybe"
    worth_it = "worth_it"

# This is the OLD enum (now for spaces)
class VibeRatingEnum(enum.Enum):
    empty = "empty"
    studying = "studying"
    lively = "lively"
    packed = "packed"

class RSVPVisibilityEnum(enum.Enum):
    public = "public"
    private = "private"

class RSVPStatusEnum(enum.Enum):
    going = "going"
    interested = "interested"
    not_interested = "not_interested"

class PhotoStatusEnum(enum.Enum):
    approved = "approved"
    flagged = "flagged"
    removed = "removed"

class RoleEnum(enum.Enum):
    student = "student"
    organizer = "organizer"

# --- Models ---

class UserAnon(Base):
    __tablename__ = "users_anon"
    # ... (no changes to this model) ...
    anon_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    created_ts = Column(DateTime(timezone=True), server_default=func.now())
    vibes = relationship("Vibe", back_populates="user")
    rsvps = relationship("RSVP", back_populates="user")
    photos = relationship("Photo", back_populates="user")
    chats = relationship("Chat", back_populates="user")

class AuthLink(Base):
    __tablename__ = "auth_links"
    
    auth0_sub = Column(String, primary_key=True)
    anon_id = Column(UUID(as_uuid=True), ForeignKey("users_anon.anon_id"), nullable=False, unique=True)
    
    user = relationship("UserAnon", backref=backref("auth_link", uselist=False, cascade="all, delete-orphan"))
    profile = relationship("UserProfile", back_populates="auth_link", uselist=False, cascade="all, delete-orphan")

class UserProfile(Base):
    __tablename__ = "user_profiles"
    
    auth0_sub = Column(String, ForeignKey("auth_links.auth0_sub"), primary_key=True)
    username = Column(String, nullable=False, unique=True, index=True)
    display_name = Column(String, nullable=True)
    bio = Column(String, nullable=True)
    profile_image_url = Column(String, nullable=True)
    role = Column(Enum(RoleEnum), nullable=False, default=RoleEnum.student)
    created_ts = Column(DateTime(timezone=True), server_default=func.now())
    
    auth_link = relationship("AuthLink", back_populates="profile")

class Event(Base):
    __tablename__ = "events"
    
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    title = Column(String, nullable=False)
    description = Column(String)
    start_time = Column(DateTime(timezone=True), nullable=False)
    end_time = Column(DateTime(timezone=True), nullable=False)
    location_lat = Column(Float)
    location_lon = Column(Float)
    location_name = Column(String)
    source_url = Column(String)
    image_url = Column(String)
    tags = Column(ARRAY(String))
    created_by = Column(UUID(as_uuid=True), ForeignKey("users_anon.anon_id"), nullable=True)
    
    # Q1 (Fixed)
    vibe_question_1_text = Column(String, nullable=False, default="Worth the trip right now?")
    vibe_question_1_options = Column(ARRAY(String), nullable=False, default=['👎 Skip', '🤷 Maybe', '👍 Worth it'])
    
    # Q2 (Contextual, generated by AI)
    vibe_question_2_text = Column(String, nullable=True)
    vibe_question_2_options = Column(ARRAY(String), nullable=True) # e.g., ['❌ Gone', '🟨 Limited', '🍕 Plenty']

class Space(Base):
    __tablename__ = "spaces"
    
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    name = Column(String, nullable=False, unique=True)
    type = Column(String, nullable=False) 
    lat = Column(Float)
    lon = Column(Float)

# --- Vibe Model (HEAVILY UPDATED) ---
class Vibe(Base):
    __tablename__ = "vibes"
    
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    target_type = Column(Enum(VibeTargetEnum), nullable=False)
    target_id = Column(UUID(as_uuid=True), nullable=False, index=True) 
    anon_id = Column(UUID(as_uuid=True), ForeignKey("users_anon.anon_id"), nullable=False, index=True)
    ts = Column(DateTime(timezone=True), server_default=func.now())
    
    # --- ALL VIBE FIELDS (OLD AND NEW) ---
    
    # Q1 (for Events)
    worth_it_rating = Column(Enum(WorthItRatingEnum), nullable=True)
    # Q2 (for Events)
    contextual_answer = Column(String, nullable=True)
    
    # Old system (for Spaces)
    rating_enum = Column(Enum(VibeRatingEnum), nullable=True)
    food_rating = Column(Integer, nullable=True)
    crowd_rating = Column(Integer, nullable=True)
    queue_rating = Column(Integer, nullable=True)
    
    user = relationship("UserAnon", back_populates="vibes")

class RSVP(Base):
    __tablename__ = "rsvps"
    
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    event_id = Column(UUID(as_uuid=True), ForeignKey("events.id"), nullable=False, index=True)
    anon_id = Column(UUID(as_uuid=True), ForeignKey("users_anon.anon_id"), nullable=False, index=True)
    visibility = Column(Enum(RSVPVisibilityEnum), nullable=False, default=RSVPVisibilityEnum.private)
    status = Column(Enum(RSVPStatusEnum), nullable=False)
    ts = Column(DateTime(timezone=True), server_default=func.now())
    
    user = relationship("UserAnon", back_populates="rsvps")
    
class Photo(Base):
    __tablename__ = "photos"
    
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    target_type = Column(Enum(VibeTargetEnum), nullable=False)
    # --- THIS IS THE CHANGE ---
    target_id = Column(UUID(as_uuid=True), nullable=True, index=True) # Changed to nullable=True
    # --- END OF CHANGE ---
    anon_id = Column(UUID(as_uuid=True), ForeignKey("users_anon.anon_id"), nullable=False, index=True)
    url = Column(String, nullable=False)
    nsfw_score = Column(Float)
    status = Column(Enum(PhotoStatusEnum), nullable=False, default=PhotoStatusEnum.approved)
    ts = Column(DateTime(timezone=True), server_default=func.now())
    
    user = relationship("UserAnon", back_populates="photos")

class Chat(Base):
    __tablename__ = "chats"
    
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    channel = Column(String, nullable=False, index=True)
    anon_id = Column(UUID(as_uuid=True), ForeignKey("users_anon.anon_id"), nullable=False, index=True)
    message = Column(String, nullable=False)
    ts = Column(DateTime(timezone=True), server_default=func.now())
    moderation_flag = Column(Boolean, default=False)
    
    user = relationship("UserAnon", back_populates="chats")
    
class EventFeedback(Base):
    __tablename__ = "event_feedback"
    
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    event_id = Column(UUID(as_uuid=True), ForeignKey("events.id"), nullable=False, index=True)
    anon_id = Column(UUID(as_uuid=True), ForeignKey("users_anon.anon_id"), nullable=False, index=True)
    
    rating = Column(Integer, nullable=False) # 1-5
    review = Column(String, nullable=True)
    ts = Column(DateTime(timezone=True), server_default=func.now())
    
    # Relationships
    event = relationship("Event")
    author = relationship("UserAnon")